name: ESMeta New 'Yet' Phrases Detection

on: [pull_request]

jobs:
  esmeta-new-phrases:
    runs-on: ubuntu-latest

    env:
      ESMETA_HOME: vendor/esmeta

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup SBT
        uses: sbt/setup-sbt@v1
      - name: download esmeta
        run: |
          mkdir -p "${ESMETA_HOME}"
          cd "${ESMETA_HOME}"
          git init
          git remote add origin https://github.com/es-meta/esmeta.git
          git fetch --depth 1 origin a9b543cc0ae8d467f9b67d03a48aeb2494cb57bf ;
          git checkout FETCH_HEAD
      - name: build esmeta
        run: |
          cd "${ESMETA_HOME}"
          sbt assembly
      - name: link
        run: |
          rmdir "${ESMETA_HOME}"/ecma262 \
            && ln -s "$(pwd)" "${ESMETA_HOME}"/ecma262

      - id: collect
        name: List added line numbers
        shell: bash
        env:
          FILE_PATH: spec.html
          BASE_SHA: ${{ github.event.pull_request.base.sha }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }} # should use github.sha ?
        run: |
          # zero-context diff, limited to the file we care about
          added_lines=$(git diff -U0 --no-color "${BASE_SHA}" "${HEAD_SHA}" -- "${FILE_PATH}" |
          # keep only the hunk headers (the @@ lines)
          awk '
            # Example header: @@ -158,0 +159,2 @@
            /^@@/ {
              # Extract “+<start>[,<count>]” part
              match($0, /\+([0-9]+)(,([0-9]+))?/, a)
              start = a[1]
              count = (a[3] == "" ? 1 : a[3])
              # Print every line number in the added range
              for (i = 0; i < count; i++) print start + i
            }
          ')

          added_lines_json="[$(echo "$added_lines" | paste -sd "," -)]"
          echo "added_lines=$added_lines_json" >> "$GITHUB_OUTPUT"

      - name: check newly introduces phrases
        run: |
          "${ESMETA_HOME}"/bin/esmeta extract \
            -status \
            -extract:warn-action <<< ${{ steps.collect.outputs.added_lines }}

